### ISSUE TITLE
White page?

### ISSUE THREAD

**Issue by woeterman94** [ChrisZieba/blackjack#1]
Not working?

I only get a white page... Even after running the grunt command. Can you please put a working example in your example folder?

**Comment by ChrisZieba** [comment]
@woeterman94 what exactly are you trying to do, can you paste some code? There is a usage example in the readme: https://github.com/ChrisZieba/blackjack/blob/master/README.md. I'm guessing you're trying to build something similar to http://chriszieba.com/2015/03/30/blackjack-probabilities?

**Comment by ChrisZieba** [comment]
Feel free to reopen with some more info.
